version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tksh_codebase_db
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
